=== rupindersandhu/lab07/data/Lab7dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT timetable (dayofweek|timeslot|course)+>
<!ELEMENT dayofweek (class*)>
<!ATTLIST dayofweek
    day (monday|tuesday|wednesday|thursday|friday) #REQUIRED
>
<!ELEMENT timeslot (class*)>
<!ATTLIST timeslot
    time (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
>
<!ELEMENT course (class+)>
<!ATTLIST course
    coursecode (BLAW3600|COMP4560|COMP4735|COMP4945|COMP4941|COMP4711) #REQUIRED
>
<!ELEMENT class (room, instructor, type)>
<!ATTLIST class
    coursecode (BLAW3600|COMP4560|COMP4735|COMP4945|COMP4941|COMP4711) #REQUIRED
    day (monday|tuesday|wednesday|thursday|friday) #REQUIRED
    starttime (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
    endtime (0930|1030|1130|1230|1330|1430|1530|1630|1730) #REQUIRED
>
<!ELEMENT room (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type classtype (Lab|Lec) #REQUIRED >

=== rupindersandhu/lab07/data/lab7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>


<!DOCTYPE timetable SYSTEM "Lab7dtd.dtd" >

<timetable>
    <dayofweek day = "monday">
        <class coursecode = "COMP4560" day = "monday" starttime = "0830" endtime = "1030" >
            <room>SE12-320</room>
            <instructor>Brenda Fine</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "COMP4735" day = "monday" starttime = "1130" endtime = "1230">
            <room>SW1-1205</room>
            <instructor>Mirela Gutica</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "COMP4735" day = "monday" starttime = "1530" endtime = "1730">
            <room>SE12-322</room>
            <instructor>Matthew Linder</instructor>
            <type classtype="Lab"></type>
        </class>
    </dayofweek>

    <dayofweek day = "tuesday">
        <class coursecode = "COMP4560" day = "tuesday" starttime = "1130" endtime = "1230" >
            <room>SW5-1850</room>
            <instructor>Brenda Fine</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "COMP4711" day = "tuesday" starttime = "1230" endtime = "1430">
            <room>SE12-320</room>
            <instructor>James Parry</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "COMP4711" day = "tuesday" starttime = "1430" endtime = "1530">
            <room>SW5-1840</room>
            <instructor>James Parry</instructor>
            <type classtype="Lec"></type>
        </class>
    </dayofweek>

    <dayofweek day = "wednesday">
        <class coursecode = "COMP4735" day = "wednesday" starttime = "0930" endtime = "1030" >
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "COMP4735" day = "wednesday" starttime = "1030" endtime = "1130">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "COMP4735" day = "wednesday" starttime = "1330" endtime = "1430">
            <room>SW1-1205</room>
            <instructor>Mirela Gutica</instructor>
            <type classtype="Lec"></type>
        </class>
    </dayofweek>

    <dayofweek day = "thursday">
        <class coursecode = "BLAW3600" day = "thursday" starttime = "0930" endtime = "1130">
            <room>SW3-2620</room>
            <instructor>Katherine Ryan</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "COMP4735" day = "thursday" starttime = "1130" endtime = "1230" >
            <room>SW3-1710</room>
            <instructor>Mirela Gutica</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "COMP4945" day = "thursday" starttime = "1330" endtime = "1730">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
    </dayofweek>

    <dayofweek day = "friday">
        <class coursecode = "BLAW3600" day = "friday" starttime = "0830" endtime = "1030" >
            <room>SW5-1840</room>
            <instructor>Kevin Wainwright</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "BLAW3600" day = "friday" starttime = "1230" endtime = "1430">
            <room>SW3-1750</room>
            <instructor>Brenda Fine</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "COMP4941" day = "friday" starttime = "1330" endtime = "1730">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
    </dayofweek>
    <!--
    Timeslot view of COMP4G's schedule, including times: 830, 930, 1030, 1130
    -->
    <timeslot time="0830">
        <class coursecode = "COMP4560" day = "tuesday" starttime="0830" endtime="1030">
            <room>SE12-320</room>
            <instructor>Brenda Fine</instructor>  
            <type classtype="Lab"></type>
        </class>  
        <class coursecode="BLAW3600" day="friday" starttime="0830" endtime="1030">
            <room>SW5-1840</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype="Lec"></type>
        </class>
    </timeslot>
    
    <timeslot time="0930">
        <class coursecode = "COMP4560" day = "monday" starttime="0830" endtime="1030">
            <room>SE12-320</room>
            <instructor>Brenda Fine</instructor>           
            <type classtype="Lab"></type>
        </class>  
        <class coursecode = "COMP4945" day = "wednesday" starttime = "0930" endtime = "1030">
            <room>SE12-310</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "BLAW3600" day = "thursday" starttime = "0930" endtime = "1130">
            <room>SW3-2620</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode="BLAW3600" day="friday" starttime="0830" endtime="1030">
            <room>SW5-1840</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype="Lec"></type>
        </class>
    </timeslot>
    
    <timeslot time="1030">
        <class coursecode = "COMP4941" day = "wednesday" starttime = "1030" endtime = "1130">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype="Lab"></type>
        </class>
        <class coursecode = "BLAW3600" day = "thursday" starttime = "0930" endtime = "1130">
            <room>SW3-2620</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype="Lab"></type>
        </class>
    </timeslot>
    
    <timeslot time="1130">
        <class coursecode="COMP4735" day="monday" starttime="1130" endtime="1230">
            <room>SW1-1205</room>
            <instructor>Mirela Gutica</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode="COMP4560" day="tuesday" starttime="1130" endtime="1230">
            <room>SW5-1850</room>
            <instructor>Brenda Fine</instructor>
            <type classtype="Lec"></type>
        </class>
        <class coursecode="COMP4735" day="thursday" starttime="1130" endtime="1230">
            <room>SW3-1710</room>
            <instructor>Mirela Gutica</instructor>
            <type classtype="Lec"></type>
        </class>
    </timeslot>
    
    <course coursecode = "COMP4560">
        <class coursecode = "COMP4560" day = "monday" starttime="0830" endtime="1030">
            <room>SE12-320</room>
            <instructor>Brenda Fine</instructor>      
            <type classtype="Lab"></type>
        </class>  
        <class coursecode = "COMP4560" day = "tuesday" starttime="1130" endtime="1230">
            <room>SW5-1850</room>
            <instructor>Brenda Fine</instructor>   
            <type classtype="Lec"></type>
        </class>
        <class coursecode = "COMP4560" day = "friday" starttime="1230" endtime="1330">
            <room>SW3-1750</room>
            <instructor>Brenda Fine</instructor>       
            <type classtype="Lec"></type>
        </class>  
    </course>
    
    <course coursecode= "BLAW3600">
        <class coursecode ="BLAW3600" day = "thursday" starttime="0930" endtime="1130">
            <room>SW3-2620</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype = "Lab"></type>
        </class>
        <class coursecode ="BLAW3600" day = "friday" starttime="0830" endtime="1030">
            <room>SW5-1840</room>
            <instructor>Catherine Ryan</instructor>
            <type classtype = "Lec"></type>
        </class>
    </course>
    
    <course coursecode = "COMP4941">
        <class coursecode = "COMP4941" day = "friday" starttime = "1330" endtime = "1730">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype = "Lec"></type>
        </class>
        <class coursecode = "COMP4941" day = "wednesday" starttime = "1030" endtime = "1130">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype = "Lab"></type>
        </class>
    </course>
    
    <course coursecode = "COMP4945">
        <class coursecode = "COMP4945" day = "thursday" starttime = "1330" endtime = "1730">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype = "Lab"></type>
        </class>
        <class coursecode = "COMP4945" day = "wednesday" starttime = "0930" endtime = "1030">
            <room>SE12-319</room>
            <instructor>Tejinder Randhawa</instructor>
            <type classtype = "Lec"></type>
        </class>
    </course>
    
    <course coursecode = "COMP4711">
        <class coursecode ="COMP4711" day = "tuesday" starttime = "1430" endtime = "1530">
            <room>SW5-1840</room>
            <instructor>James Parry</instructor>
            <type classtype = "Lec"></type>
        </class>
        <class coursecode ="COMP4711" day = "tuesday" starttime = "1230" endtime = "1430">
            <room>SE12-320</room>
            <instructor>James Parry</instructor>
            <type classtype = "Lab"></type>
        </class>
    </course>
</timetable>
